apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rival-tyrannosaurus-go 
  janus-idp.io/tekton: rival-tyrannosaurus-go
  backstage.io/kubernetes-id: rival-tyrannosaurus-go
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: rival-tyrannosaurus-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  