apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rival-tyrannosaurus-go
  janus-idp.io/tekton: rival-tyrannosaurus-go
  backstage.io/kubernetes-id: rival-tyrannosaurus-go
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: rival-tyrannosaurus-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
